package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
)

type AutoGenerated struct {
	Paltas []string `json:"paltas"`
}

func homePage(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpoint Hit: homePage")

	paltas := []string{"hass", "fuerte", "criollo", "choquette", "bacon", "pinkerton"}

	js, err := json.Marshal(paltas)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write(js)
}

func handleRequests() {
	http.HandleFunc("/", homePage)
	fmt.Println("Running server")
	log.Fatal(http.ListenAndServe(":80", nil))
}

func main() {
	handleRequests()
}
